create table players(
    id bigint generated by default as identity,
    name varchar(255),
    age integer,
    player_position varchar(255),
    averageScore double,
    primary key (id)
);

create table games(
    id bigint generated by default as identity,
    homeTeam varchar(255),
    teamScore integer,
    awayTeam varchar(255),
    awayScore integer,
    primary key(id)
);

