create table books (
    id bigint generated by default as identity,
    title varchar,
    author varchar,
    primary key(id)
);

create table reviews (
    id bigint generated by default as identity,
    reviewer varchar,
    content varchar,
    rating varchar,
    book_id bigint,
    primary key(id),
    foreign key(book_id) references books
);