package spring.jpa.entitymanagerrepo;

import javax.persistence.*;

@Entity //<-- the entity name is the class name(Book) which is used in your JPQL
@Table(name = "books")
public class Book {
    @Id //<-- This field is the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) //<-- this field is autogenerated by the DB
    private long id;
    private String title;
    private String author;

    // Hibernate requires a no-args contructor to create a book object from a JDBC resultSet
    public Book() {
    }

    public Book(String title, String author) {
        this.title = title;
        this.author = author;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }
}
