
--when using an embedded in memory DB(like h2) this file will be executed against the DB on startup
create table clients (
    id bigint generated by default as identity,
    email varchar(255),
    name varchar(255),
    primary key (id)
);
